spring:
  data.r2dbc.repositories:
    enabled: true
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: "r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public"
  flyway:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public"
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

